stages:
  data_ingestion:
    cmd: python src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-data


  prepare_base_model:
    cmd: python src/CNN_Classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/CNN_Classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/CNN_Classifier/pipeline/stage_03_model_training.py
    deps:
      - src/CNN_Classifier/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-data
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.keras


  evaluation:
    cmd: python src/CNN_Classifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/CNN_Classifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-data
      - artifacts/training/model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false